<?php

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

/**
 * An example global include file.
 *
 * We don't actually use this file.  But if we delete it, BLT will recreate it
 * during the build process, then the continuous integration build will fail
 * because there's a source file which isn't in source control.
 *
 * So, we end up with extra code in global.settings.php in order to ignore it.
 */

/**
 * Include settings files in docroot/sites/settings.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 */
$additionalSettingsFiles = [
  // e.g,( DRUPAL_ROOT . "/sites/settings/foo.settings.php" )
];

foreach ($additionalSettingsFiles as $settingsFile) {
  if (file_exists($settingsFile)) {
    require $settingsFile;
  }
}
