<?php

/**
 * Include custom global settings files.
 *
 * This is intended for to provide an opportunity for applications to override
 * any previous configuration at a global or multisite level.
 *
 * This is included by vendor/acquia/blt/settings/blt.settings.php, before the CI
 * and site specific settings files.
 *
 ***********************************************************************************
 * This logic supports the old behavior of loading all files in the settings folder.
 * However, there may be times when supporting files, or in the case of default.global.settings.php
 * that is automatically added by BLT, must not be loaded because they are NOT settings.
 * the excludeFiles array is for ignoring those non-settings files.
 *
 * In the case of local.settings.php, this file is loaded by BLT sometime AFTER
 * global.settings.php has been run.
 ***********************************************************************************
 */

// Don't load these files.
$excludeFiles = [
  __FILE__,   // This file.
  DRUPAL_ROOT . '/sites/settings/default.global.settings.php', // Sample generated by BLT.
  DRUPAL_ROOT . '/sites/settings/local.settings.php',          // Loaded later.
];

if ($settings_files = array_filter(
    glob(DRUPAL_ROOT . '/sites/settings/*.settings.php'),
    function($file) use ($excludeFiles) { return !in_array($file, $excludeFiles); })
  ) {
  foreach ($settings_files as $settings_file) {
    require $settings_file;
  }
}
