<?php

/**
 * Include custom global settings files.
 *
 * This is intended for to provide an opportunity for applications to override
 * any previous configuration at a global or multisite level.
 *
 * This is included by
 * vendor/acquia/acquia-recommended-settings/settings/acquia-recommended.settings.php,
 * before the CI and site specific settings files.
 *
 ***********************************************************************************
 * This logic supports the old behavior of loading all files in the settings folder.
 * However, there may be times when supporting files, or in the case of default.global.settings.php
 * that is automatically added by Acquia Recommended Settings, must not be loaded because they
 * are NOT settings. The excludeFiles array is for ignoring those non-settings files.
 *
 * In the case of local.settings.php, this file is loaded by Acquia Recommended Settings sometime
 * AFTER global.settings.php has been run.
 ***********************************************************************************
 */

// Don't load these files.
$excludeFiles = [
  __FILE__,   // This file.
  DRUPAL_ROOT . '/sites/settings/default.global.settings.php', // Sample generated by BLT.
  DRUPAL_ROOT . '/sites/settings/local.settings.php',          // Loaded later.
];

if ($settings_files = array_filter(
    glob(DRUPAL_ROOT . '/sites/settings/*.settings.php'),
    function($file) use ($excludeFiles) { return !in_array($file, $excludeFiles); })
  ) {
  foreach ($settings_files as $settings_file) {
    require $settings_file;
  }
}

/*
 * DDev wants to add the following to settings.php. We would like to leave that
 * untouched, so we will add after all the other general config options. We do
 * need to leave the settings.ddev.php in the folder with settings.php though,
 * since ddev can make changes there.
 */
if (getenv('IS_DDEV_PROJECT') == 'true') {
  $ddev_settings = __DIR__ . '/../default' . '/settings.ddev.php';
  if (is_readable($ddev_settings)) {
    require $ddev_settings;
  }
}
