name: 'CGov HTTPS Enforcement Configuration'
type: module
package: 'CGov HTTPS Enforcement Configuration'
description: 'Configures enforcement of HTTPS'
core_version_requirement: ^8.9 || ^9
dependencies:
  - seckit
