name: 'CGov HTTPS Enforcement Configuration'
type: module
package: 'CGov HTTPS Enforcement Configuration'
description: 'Configures enforcement of HTTPS'
core_version_requirement: '^9.4 || ^10'
dependencies:
  - seckit
