features.assignment.cgov_alter:
  type: features.assignment.settings
  label: "Cgov Alter"
  mapping:
    workflow:
      type: boolean
      label: "Workflow"
    saml:
      type: boolean
      label: "SAML config for Single Sign-On"
