<?php

use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;

/**
 * Modify the list of available CKEditor 5 plugins.
 * implements hook_ckeditor5_plugin_info_alter()

 * Replace drupal core's table plugin with our own.
 *
 * @param array $plugin_definitions
 *   An array of all the existing plugin definitions, passed by reference.
 *
 * @see \Drupal\ckeditor5\Plugin\CKEditor5PluginManager
 */
function cgov_ckeditor_hack_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {

  assert($plugin_definitions['ckeditor5_table'] instanceof CKEditor5PluginDefinition);

  //$html_support_plugin_defintion = $plugin_definitions['ckeditor5_htmlSupport'];//->toArray();
  $source_editing_plugin_definition = $plugin_definitions['ckeditor5_sourceEditing']->toArray();
  $style_plugin_defintion = $plugin_definitions['ckeditor5_style']->toArray();
  $table_plugin_defintion = $plugin_definitions['ckeditor5_table']->toArray();

  $substitution = [
    'ckeditor5_sourceEditing' => 'cgov_ckeditor_hack/ckeditor5.sourceEditing',
    'ckeditor5_style' => 'cgov_ckeditor_hack/ckeditor5.style',
    'ckeditor5_table' => 'cgov_ckeditor_hack/ckeditor5.table'
  ];

  foreach($substitution as $key => $replacement) {
    assert($plugin_definitions[$key] instanceof CKEditor5PluginDefinition);
    $plugin = $plugin_definitions[$key]->toArray();
    $plugin['drupal']['library'] = $replacement;
    $plugin_definitions[$key] = new CKEditor5PluginDefinition($plugin);

    //file_put_contents("$key.txt", var_export($replacement, TRUE));
  }

}
