<?php

/**
 * @file
 * Hook implementations for content syndication.
 */

use Drupal\node\Entity\Node;
use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_preprocess_html().
 */
function cgov_syndication_preprocess_html(&$variables) {

  // Add the `meta` information we need for syndicated content.
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!empty($node) && $node instanceof Node) {
    if ($node->hasField('field_hhs_syndication')) {
      $tools = \Drupal::service('cgov_core.tools');
      $canonical = $node->toUrl('canonical')->toString();
      $prod_url = \rtrim($tools->getProdUrl(), '/');
      $variables['syndication_canonical'] = "$prod_url$canonical";
      $keywords = $node->field_hhs_syndication->keywords;
      $variables['syndication_keywords'] = $keywords;
      $description = $node->field_page_description->value;
      $variables['syndication_description'] = $description;
    }
  }
}

/**
 * Implements hook_ENTITY_insert().
 *
 * Perform any actions that are required when adding a new language.
 * During the install process, only EN is enabled, so use this hook
 * to add any other translations or other things needed by a new
 * language when it gets enabled.
 *
 * Adds new Syndication message translation when a new language is installed.
 */
function cgov_syndication_configurable_language_insert($entity) {
  $syndication_message['es'] = <<<EOMarkup
  <svg class="usa-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 48 48" fill="none"><path fill="#1B1B1B" fill-rule="evenodd" d="M19.616 12h21.818A2.57 2.57 0 0 1 44 14.575v15.24a2.57 2.57 0 0 1-2.567 2.567H28.937a.645.645 0 0 1-.618-.465c-.067-.228.152-.625.324-.936.034-.06.066-.119.093-.171l.102-.198c.232-.454.544-1.064.99-1.446a.653.653 0 0 1 .424-.16h10.38V15.368H20.699l-.024 3.634c.008.256-.056.497-.265.641-.2.145-.449.097-.69.024l-2.382-.722a.645.645 0 0 1-.305-.44l.016-1.34v-2.6A2.57 2.57 0 0 1 19.616 12Zm8.68 12.353a.613.613 0 0 1 .368.337c.064.152.064.337-.032.417l-4.86 9.874a.603.603 0 0 1-.554.337.587.587 0 0 1-.53-.361l-1.652-3.85c-6.209 2.454-10.468.69-12.97-1.268-2.174-1.7-3.394-3.786-3.843-4.66a6.678 6.678 0 0 1-.2-.417.598.598 0 0 1 1.123-.401c.006.025.026.068.057.135l.031.065c2.19 4.468 10.765 3.089 13.46 1.1l-1.629-3.803a.593.593 0 0 1 .722-.802l10.508 3.297Z" clip-rule="evenodd"/></svg>
  <p>¿Desea usar este contenido en su sitio web o en otra plataforma digital? En nuestra <a class="usa-link" href="/espanol/sindicacion">página de sindicación de contenidos</a> le decimos cómo hacerlo.</p>
EOMarkup;

  $langcode = $entity->id();

  // If no translation defined, exit hook.
  if (!isset($syndication_message[$langcode])) {
    return;
  }

  // Get the existing English Syndication message block to add the translation.
  $block_storage = \Drupal::entityTypeManager()->getStorage('block_content');
  $result = $block_storage->getQuery()
      ->accessCheck(FALSE)
      ->condition('info', 'Syndication Message')
      ->condition('langcode', 'en')
      ->execute();
  if (count($result)) {
    $eid = array_shift($result);
    $block = $block_storage->load($eid);
    if ($block === NULL) {
      return;
    }
    $title = $block->info->value . " - " . $langcode;
    // Create translation if it doesn't already exist.
    if ($block instanceof BlockContent && !$block->hasTranslation($langcode)) {
      $block_translated = $block->addTranslation($langcode, [
        'id' => "syndication_message__$langcode",
        'info' => $title,
        'field_raw_html' => ['value' => $syndication_message[$langcode], 'format' => 'raw_html'],
      ]);
      $block_translated->save();
      \Drupal::messenger()->addStatus('Added Syndication Message block_content: ' . $title);
    }
  }
}
