<?php

/**
 * @file
 * Contains cgov_core.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Render\Element;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Cache\Cache;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_entity_translation_create().
 *
 * Corrects the initial moderation state for a new translation.
 * The hook is called when a new translation is created, giving us
 * the opportunity to modify the object for that translation. We're
 * setting the initial moderation state for the translation, and
 * that in turn is used by the logic which determines which states
 * are available when the new translation is save. The bug for which
 * this workaround is implemented just copies the initial state from
 * the current state of the original language. When the Drupal core
 * team fixes https://www.drupal.org/project/drupal/issues/3021222,
 * this workaround can be removed.
 *
 * See https://github.com/NCIOCPL/cgov-digital-platform/issues/371
 * for more details about the bug and exactly what the software is
 * doing.
 *
 * @var Drupal\Core\Entity\EntityInterface $translation
 *   The entity object for the new translation of a content object.
 */
function cgov_core_entity_translation_create(EntityInterface $translation) {
  $serviceName = 'content_moderation.moderation_information';
  $moderationInformation = \Drupal::service($serviceName);
  if ($moderationInformation->isModeratedEntity($translation)) {
    $workflow = $moderationInformation->getWorkflowForEntity($translation);
    $configuration = $workflow->getTypePlugin()->getConfiguration();
    $state = 'draft';
    if (!empty($configuration['default_moderation_state'])) {
      $state = $configuration['default_moderation_state'];
    }
    $translation->moderation_state = $state;
  }
}

/**
 * Implements hook_block_build_alter().
 *
 * Set cache context of blocks that vary by url, user, etc.
 */
function cgov_core_block_build_alter(array &$build, BlockPluginInterface $block) {
  // Get name of block's label (will be of
  // originally-created block if translations exist).
  $block_label = $block->getPluginDefinition()['admin_label'];

  // Add the 'url' cache context to page-specific blocks.
  if (strpos($block_label, 'Public Use') === 0) {
    $build['#cache']['contexts'][] = 'url';

    // Add the 'node' cache context so node updates are caught.
    $route_name = \Drupal::routeMatch()->getRouteName();
    if ($route_name == 'entity.node.canonical') {
      // Store the NID of the current node.
      $nid = \Drupal::routeMatch()->getRawParameter('node');
      $build['#cache']['tags'][] = "node:$nid";
    }
    // If not the node view page (eg: Preview or Latest) don't cache block.
    else {
      $build['#cache']['max_age'] = 0;
    }
  }
}

/**
 * Implements hook_ENTITY_insert().
 *
 * Perform any actions that are required when adding a new language.
 * During the install process, only EN is enabled, so use this hook
 * to add any other translations or other things needed by a new
 * language when it gets enabled.
 *
 * Adds new Public Use translation when a new language is installed.
 */
function cgov_core_configurable_language_insert($entity) {
  $public_use['es'] = <<<EOMarkup
<p><em>Si desea copiar algo de este texto, vea <a href="/espanol/politicas/derechos-de-autor-y-uso">Derechos de autor y uso de imágenes y contenido</a> sobre instrucciones de derechos de autor y permisos. En caso de reproducción digital permitida, por favor, dé crédito al Instituto Nacional del Cáncer como su creador, y enlace al producto original del NCI usando el título original del producto; por ejemplo,  “[current-page:title] publicada originalmente por el Instituto Nacional del Cáncer.”</em></p>
EOMarkup;

  $langcode = $entity->id();

  // If no translation defined, exit hook.
  if (!isset($public_use[$langcode])) {
    return;
  }

  // Get the existing English PublicUse block to add the translation.
  $query = \Drupal::entityQuery('block_content');
  $query->condition('info', 'Public Use')
    ->condition('langcode', 'en');
  $result = $query->execute();
  if (count($result)) {
    $eid = array_shift($result);
    $block = entity_load('block_content', $eid);
    $title = $block->info->value . " - " . $langcode;
    // Create translation if it doesn't already exist.
    if (!$block->hasTranslation($langcode)) {
      $block_translated = $block->addTranslation($langcode, [
        'id' => "public_use__$langcode",
        'info' => $title,
        'body' => ['value' => $public_use[$langcode], 'format' => 'full_html'],
      ]);
      $block_translated->save();
      drupal_set_message("Added Public Use block_content: $title");
    }
  }
}

/**
 * Implements hook_node_access().
 */
function cgov_core_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $publish_permission = 'use editorial_workflow transition publish';
  switch ($op) {

    // Currently we only have something to say about deletions.
    case 'delete':

      // Only weigh in for content controlled by `editorial_workflow`.
      $entityTypeManager = \Drupal::service('entity_type.manager');
      $workflows = $entityTypeManager->getStorage('workflow')->loadMultiple();
      $workflow = $workflows['editorial_workflow'];
      $typePlugin = $workflow->getTypePlugin();
      if (!$typePlugin->appliesToEntityTypeAndBundle('node', $node->bundle())) {
        break;
      }

      // Authors can only delete nodes in the `draft` state, and only if the
      // node has never been published.
      $state = $node->moderation_state->value;
      if (!$account->hasPermission($publish_permission)) {
        $reason = 'Authors not allowed to delete content ';
        if ($state !== 'draft') {
          $reason .= "in '$state' moderation state";
          return AccessResult::forbidden($reason);
        }
        $query = \Drupal::database()->select('node_field_revision', 'r');
        $query->condition('r.status', 1);
        $query->condition('r.nid', $node->id());
        if ($query->countQuery()->execute()->fetchField() > 0) {
          $reason .= 'which has ever been published';
          return AccessResult::forbidden($reason);
        }
      }
      else {

        // Editors can also delete nodes which are in the `archived` state.
        if ($state !== 'draft' && $state !== 'archived') {
          $reason = "Content in '$state' moderation state cannot be deleted";
          return AccessResult::forbidden($reason);
        }
      }
      break;

    // Let other modules weigh in for nodes whose deletion we haven't vetoed.
    default:
      return AccessResult::neutral();
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 *
 * Validates that the PubMed ID Field on Citations
 * matches the required pattern.
 */
function cgov_core_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if (($bundle == 'cgov_citation') && !empty($fields['field_pubmed_id'])) {
    $fields['field_pubmed_id']->setPropertyConstraints('value', [
      'Regex' => [
        'pattern' => '/^[0-9]*$/',
        'message' => 'The PubMed ID field only accepts numbers.',
      ],
    ]
    );
  }
}

/**
 * Implements hook_field_widget_form_alter().
 *
 * Limits allowed text formats using the cgov_core form_tools service.
 */
function cgov_core_field_widget_form_alter(&$element, $form_state, $context) {
  // Maps field names to an array containing a single format.
  $map = [
    'field_citation_content' => ['streamlined'],
    'field_intro_text' => ['streamlined'],
    'field_caption' => ['simple'],
    'body' => ['full_html'],
  ];
  $formHelper = \Drupal::service('cgov_core.form_tools');
  $formHelper->allowTextFormats($map, $element, $context);
}

/**
 * Implements hook_entity_presave().
 *
 * When a user is initially created, default the preferred
 * language for the UI pages to English.
 */
function cgov_core_user_presave(EntityInterface $entity) {
  if ($entity->isNew()) {
    $entity->set('preferred_admin_langcode', 'en');
  }
}

/**
 * Implements hook_form_alter().
 *
 * We want to remove the 'Reset by Alphabetical'
 * form button on taxonomy tree forms.
 */
function cgov_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'taxonomy_overview_terms') {
    if (isset($form['actions']) && isset($form['actions']['reset_alphabetical'])) {
      unset($form['actions']['reset_alphabetical']);
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 *
 * Add attributes to media content types.
 */
function cgov_core_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  // If accessible text is available, add a link to an alternate version of the
  // page containing only the accessible text.
  // NOTE: $entity already reflects the current language, no need to switch
  // to another translation to check for availability.
  if ($entity->field_accessible_version != NULL &&
    (count($entity->field_accessible_version) > 0)) {

    // Set the longdesc attribute to a URL pointing to the infographic module's
    // route for outputing the long description.
    $args = ['media' => $entity->id()];

    // Find any field with a type of 'image' with the 'article' crop applied
    // and add the longdesc property to its attribute list.
    foreach ($build as $key => $properties) {
      if (substr($key, 0, 6) == 'field_' &&
        array_key_exists('#field_type', $properties)) {

        // Added if to prevent attempt at accessing the #field-type property if
        // it doesn't exist. (For whatever reason, evaluation doesn't seem to be
        // short-circuted when the other conditions are false.)
        if ($properties['#field_type'] == 'image' && $properties[0]["#image_style"] == 'cgov_article') {
          $build[$key][0]['#item_attributes']['longdesc'] =
            Url::fromRoute('cgov_core.long_description', $args)->toString();
        }
      }
    }
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * Workaround for odd behavior of the `getTableJoin()` method of the
 * `HandlerBase` of the `views` module, which leaves us without a table
 * alias for the queries used for sorting and filtering by bundle name.
 * If you find yourself with too much time on your hands, you might want
 * to track down enough information to file a bug report against Drupal
 * core.
 */
function cgov_core_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  $view_id = $view->id();
  if ($view_id === 'moderated_media') {
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if ($condition['field'] === '.bundle') {
          $condition['field'] = 'media.bundle';
        }
      }
    }
    foreach ($query->orderby as &$orderby) {
      if ($orderby['field'] === '.bundle') {
        $orderby['field'] = 'media.bundle';
      }
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function cgov_core_page_attachments_alter(array &$attachments) {
  $config = \Drupal::config('cgov_core.frontend_globals');
  $settings = $config->get('config_object');
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#value' => "window.CDEConfig = $settings;",
    ],
    'CDEConfig',
  ];
  $cache_tags = isset($attachments['#cache']['tags']) ? $attachments['#cache']['tags'] : [];
  $attachments['#cache']['tags'] = Cache::mergeTags($cache_tags, $config->getCacheTags());
}

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * The entity embed module does not allow suggestions for the various display
 * modes. This has been ok, except for the fact that with inline images we
 * really do not want the container wrapper rendered.
 */
function cgov_core_theme_suggestions_entity_embed_container(array $variables) {
  $suggestions = [];

  $original_hook = $variables['theme_hook_original'];
  $display = $variables['element']['#attributes']['data-entity-embed-display'];
  if ($display) {
    $sugg = str_replace("view_mode:", "", $display);
    $suggestions[] = $original_hook . '__' . $sugg;
  }

  return $suggestions;
}

/**
 * Implements hook_language_switch_links_alter().
 *
 * The default language switcher shows all links to content, including the
 * current language. It also does not care if there is no translation and
 * it does not care if the translated language has never been published.
 * We fix this, but still leverage the OOB language block.
 */
function cgov_core_language_switch_links_alter(array &$links, $type, Url $url) {
  $language_interface = \Drupal::languageManager()->getCurrentLanguage();

  // First remove the current language no matter what. This applies to all
  // links.
  unset($links[$language_interface->getId()]);

  // No links to check, we should exit.
  if (count(array_keys($links)) == 0) {
    return;
  }

  // Now is the current route a content entity?
  $entity = _cgov_core_get_curr_entity();
  if (!$entity) {
    // If this is not a content entity, then just turn off the toggles.
    $links = [];
    return;
  }

  // Get the language where there is a translated revision.
  // Note getTranslationLanguages returns interfaces and we
  // need the 2 char strings.
  $possible_langs = array_map(
    function ($lang) {
      return $lang->getId();
    },
    $entity->getTranslationLanguages(TRUE)
  );

  // There are no translations, remove links and exit.
  if (count($possible_langs) == 0) {
    $bad_langs = array_keys($links);
    foreach ($bad_langs as $lang) {
      unset($links[$lang]);
    }
    return;
  }

  // Get the list of languages that have not been translated at
  // all and remove them from the links.
  $proposed_langs = array_keys($links);
  $untranslated_langs = array_diff($proposed_langs, $possible_langs);
  foreach ($untranslated_langs as $lang) {
    unset($links[$lang]);
  }

  // Now for the remaining links, we need to check if the translation
  // has been published.
  $remaining_langs = array_keys($links);

  // There were no more links.
  if (count($remaining_langs) == 0) {
    return;
  }

  foreach ($remaining_langs as $lang) {
    $translation = $entity->getTranslation($lang);
    if (!$translation->isPublished()) {
      unset($links[$lang]);
    }
  }

}

/**
 * Gets the current entity if there is one.
 *
 * @return Drupal\Core\Entity\ContentEntityInterface
 *   The retrieved entity, or FALSE if none found.
 */
function _cgov_core_get_curr_entity() {
  $params = \Drupal::routeMatch()->getParameters()->all();
  foreach ($params as $param) {
    if (!is_object($param)) {
      continue;
    }

    $class = new \ReflectionClass($param);

    if (in_array('Drupal\Core\Entity\ContentEntityInterface', $class->getInterfaceNames())) {
      // If you find a ContentEntityInterface stop iterating and return it.
      return $param;
    }
  }
  return FALSE;
}

/**
 * Implements hook_moderation_sidebar_alter().
 *
 * We have strong opinions on what the sidebar should display and how it
 * should display them.
 * - This should never offer two ways to edit
 * - It should never show delete buttons.
 * - Workflow tasks should come first.
 * - Creating a new revision should take you to the admin edit screen.
 */
function cgov_core_moderation_sidebar_alter(array &$build, EntityInterface $entity) {

  // No actions, it is useless. We need to bail.
  if (empty($build['actions'])) {
    return;
  }

  // Remove delete button.
  if (array_key_exists('delete', $build['actions'])) {
    unset($build['actions']['delete']);
  }

  // Rename edit button in published state.
  if (!empty($build['actions']['edit'])) {
    if (
      (!empty($build['actions']['edit']['#title'])) &&
      ($build['actions']['edit']['#title']->getUntranslatedString() == 'Edit content')
    ) {
      $build['actions']['edit']['#title'] = new TranslatableMarkup("View in edit form");
    }
  }

  // Now set weights to height numbers, and we can then reorder.
  // We use Element::children to ensure we only get back render
  // elements.
  $tmp_weight = 0;
  foreach (Element::children($build['actions']) as $element) {
    $build['actions'][$element]['#weight'] = $tmp_weight + 100;
    $tmp_weight++;
  }

  $build['actions']['title'] = [
    '#markup' => t('<h3>Other Actions</h3>'),
    '#weight' => 1,
  ];

  // The workflow options should come first.
  if (!empty($build['actions']['quick_draft_form'])) {
    $build['actions']['quick_draft_form']['#weight'] = 1;
  }

  // Force the renderer to use weights instead of the order.
  $build['actions']['#sorted'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Support for cgov_core_moderation_sidebar_alter to handle components
 * of the moderation bits.
 */
function cgov_core_form_moderation_sidebar_quick_transition_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Remove Discard Draft Button.
  if (!empty($form['discard_draft'])) {
    unset($form['discard_draft']);
  }

  // Reorder a few elements.
  $tmp_weight = 0;
  foreach (Element::children($form) as $element) {
    $form[$element]['#weight'] = $tmp_weight + 100;
    $tmp_weight++;
  }

  $form['title'] = [
    '#markup' => t('<h3>Workflow Actions</h3>'),
    '#weight' => 1,
  ];

  // Move the comment checkbox and textbox above the buttons.
  if (!empty($form['revision_log_toggle'])) {
    $form['revision_log_toggle']['#weight'] = 2;
    $form['revision_log_toggle']['#title'] = new TranslatableMarkup("Add Workflow Comment");
  }
  if (!empty($form['revision_log'])) {
    $form['revision_log']['#weight'] = 3;
  }

  $form['#submit'][] = '_cgov_core_form_moderation_sidebar_quick_transition_form_submit';
}

/**
 * Submit handler for moderation_sidebar workflow actions.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The state of the form.
 */
function _cgov_core_form_moderation_sidebar_quick_transition_form_submit(array $form, FormStateInterface $form_state) {

  // List of transition IDs that cause a redirect to the edit form.
  $edit_form_transitions = [
    'revise',
    'create_new_draft',
    'back_to_draft',
    'back_to_editing',
  ];

  $triggering_elem = $form_state->getTriggeringElement();

  // If there was no triggering element, then we need to exit.
  if ($triggering_elem == NULL) {
    return;
  }

  if (!in_array($triggering_elem['#id'], $edit_form_transitions)) {
    return;
  }

  // This is how moderation_sidebar does it, and it created the form_state.
  // So we should trust this will always be here when handing that quick
  // transiton submit.
  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  $entity = $form_state->get('entity');

  $form_state->setRedirectUrl($entity->toUrl('edit-form'));
}
