name: 'CGov Single Sign-on Configuration'
type: module
package: 'CGov Single Sign-on Configuration'
description: 'Configures SimpleSAML.php Auth Settings'
core: 8.x
dependencies:
  - simplesamlphp_auth
