<?php

/**
 * @file
 * Install file for cgov_saml_auth_config.
 */

/**
 * Implements hook_install().
 */
function cgov_saml_auth_config_install() {

  // Set up permissions for roles allowed to interact with SAML config.
  $samlPermissions = [
    'administer simplesamlphp authentication',
    'change saml authentication setting',
  ];
  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');
  $siteHelper->addRolePermissions(['site_admin' => $samlPermissions]);

}
