name: 'CGov Single Sign-on Configuration'
type: module
package: 'CGov Single Sign-on Configuration'
description: 'Configures SimpleSAML.php Auth Settings'
core_version_requirement: ^8.9 || ^9
dependencies:
  - simplesamlphp_auth
