name: "CGov Single Sign-on Configuration"
type: module
package: "CGov Single Sign-on Configuration"
description: "Configures SAML Auth Settings"
core_version_requirement: ^8.9 || ^9
dependencies:
  - "autologout:autologout"
  - "samlauth:samlauth"
