cgov_adobe.settings:
  type: config_object
  mapping:
    enabled:
      type: boolean
      label: 'Adobe Tag Management enabled'
    launch_property_build_url:
      type: string
      label: 'Launch property build URL'
    exclude_paths:
      type: sequence
      label: 'Exclude Paths'
      sequence:
        type: string
        label: 'Exclude Path'
