/**
 * This file holds the entry paths for themes that gulp will use to kick off parallel builds.
 * New entries can be autogenerated by a theme skeleton building process.
 * 
 */

module.exports = [
    'cgov_common',
    'cgov_www'
];