/**
 * This file holds the entry paths for themes that gulp will use to kick off parallel builds.
 * New entries can be autogenerated by a theme skeleton building process.
 *
 */

module.exports = {
  cgov_common: {
    variants: [
      'purple',
      'blue',
      'green',
      'connect'
    ]
  }
  // Add additional sub-themes here
  // ,
  // cgov_purple: {
  //   variants: []
  // }
};
