field.formatter.settings.cgov_date_formatter:
  type: field.formatter.settings.datetime_default
  label: 'Cgov default datetime format settings'
  mapping:
    display_strategy:
      type: string
      label: 'Display Strategy'

## This is for our selection handler. It works just like
## core does, so we will inherit from that.
entity_reference_selection.cgov_all_selection:
  type: entity_reference_selection.default

cgov_core.frontend_globals:
  type: config_object
  label: 'Frontend Globals Config Object'
  mapping:
    config_object:
      type: string
      label: 'Frontend Globals JSON Config Object'

# Missing from the crop module. Without this, the unit tests fail.
media.type.*.third_party.crop:
  type: mapping
  label: 'Crop settings'
  mapping:
    image_field:
      type: string
      label: 'Field storing image to be cropped'

# Settings for the NCIDS Breadcrumb
block.settings.cgov_breadcrumb:
  type: block_settings
  label: 'NCIDS Breadcrumb block configuration'
  mapping:
    show_home_alone:
      type: string
      label: 'Root Site Section Display'

# Settings for the NCIDS Header
block.settings.ncids_header:
  type: block_settings
  label: 'NCIDS Header block configuration'
  mapping:
    home_page_title:
      type: string
      label: 'Home Page Label for Logo'
    search_results_page:
      type: uri
      label: 'Entity URI of the search results page'
    autosuggest_collection:
      type: text
      label: 'Collection name for Autosuggest API'
    logo_use_custom:
      type: boolean
      label: 'Should the header use a custom logo'
    logo_desktop_fid:
      type: integer
      label: 'Desktop logo File ID'
    logo_desktop_uri:
      type: uri
      label: 'Desktop logo URI'
    logo_mobile_fid:
      type: integer
      label: 'Mobile logo File ID'
    logo_mobile_uri:
      type: uri
      label: 'Mobile logo URI'

# SiteBranding Settings
sitebranding.settings:
  type: config_object
  label: 'Site branding Settings'
  mapping:
    browser_display_type:
      type: text
      label: 'Browser Title Site Name Display Option'
    custom_site_title_value:
      type: text
      label: 'Custom Site Title'
