field.formatter.settings.cgov_date_formatter:
  type: field.formatter.settings.datetime_default
  label: 'Cgov default datetime format settings'
  mapping:
    display_strategy:
      type: string
      label: 'Display Strategy'

## This is for our selection handler. It works just like
## core does, so we will inherit from that.
entity_reference_selection.cgov_all_selection:
  type: entity_reference_selection.default

## Capture information specific to each site.
cgov_core.site_config:
  type: config_object
  label: 'Cancer.gov site-specific settings'
  mapping:
    site:
      type: string
      label: 'The site ID'
    prod_base:
      type: string
      label: 'Production base URL'
