field.formatter.settings.cgov_date_formatter:
  type: field.formatter.settings.datetime_default
  label: 'Cgov default datetime format settings'
  mapping:
    display_strategy:
      type: string
      label: 'Display Strategy'
