<?php

/**
 * @file
 * Contains cgov_biography.install.
 */

use Drupal\block\Entity\Block;
use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function cgov_biography_install() {
  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');

  // Add content type permissions.
  $siteHelper->addContentTypePermissions('cgov_biography', ['content_author']);
}

/**
 * Implements hook_themes_installed().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_themes_installed()
 */
function cgov_biography_themes_installed(array $theme_list) {
  $supported_themes = ['ncids_trans'];
  $block_region = 'bio_press_info';
  $block_label = 'Press Information for Journalists';
  $block_html = <<<EOMarkup
    <h2>Press Contacts</h2>
    <p>To request an interview with NCI researchers, contact the NIH Press Office: <a href="mailto:nihpress@nih.gov" class="press-contact-email">nihpress@nih.gov</a>.</p>
EOMarkup;

  $block_content_entities = \Drupal::entityTypeManager()
    ->getStorage('block_content')
    ->loadByProperties(['info' => $block_label]);

  if (empty($block_content_entities)) {
    $block_content = BlockContent::create([
      'type' => 'raw_html_block',
      'info' => $block_label,
      'field_raw_html' => ['value' => $block_html, 'format' => 'raw_html'],
    ]);
    $block_content->save();
  }
  else {
    $block_content = reset($block_content_entities);
  }

  foreach ($theme_list as $theme) {
    if (!in_array($theme, $supported_themes, TRUE)) {
      // Skip doing this if a non-supported theme is being installed.
      continue;
    }

    $block_id = 'press_information_for_journalists__biography';
    if (Block::load($block_id)) {
      continue;
    }

    // Assign block to region for each supported theme as it is installed.
    $data = [
      'id' => $block_id,
      'plugin' => 'block_content:' . $block_content->uuid(),
      'region' => $block_region,
      'provider' => 'block_content',
      'weight' => 0,
      'theme' => $theme,
      'visibility' => [
        'entity_bundle:node' =>
          [
            'id' => 'entity_bundle:node',
            'negate' => FALSE,
            'context_mapping' => [
              'node' => '@node.node_route_context:node',
            ],
            'bundles' => [
              'cgov_biography' => 'cgov_biography',
            ],
          ],
        'language' =>
          [
            'id' => 'language',
            'langcodes' => ['en' => 'en'],
            'negate' => FALSE,
            'context_mapping' =>
              [
                'language' => '@language.current_language_context:language_interface',
              ],
          ],
      ],
      'settings' => [
        'label' => $block_label,
        'label_display' => '0',
      ],
    ];

    $block = Block::create($data);
    $block->save();
  }

}
