field.value.hhs_syndication:
  type: mapping
  label: 'Default value'
  mapping:
    syndicate:
      type: integer
      label: 'Is syndicated?'
    keywords:
      type: string
      label: 'Keywords for syndication'
