<?php

/**
 * @file
 * Contains cgov_infographic custom logic.
 */

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view_alter().
 *
 * Adds attributes to certain fields.
 */
function cgov_infographic_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity == NULL || $entity->bundle() != 'cgov_infographic') {
    return;
  }

  // If accessible text is available, add a link to an alternate version of the
  // page containing only the accessible text.
  if ($build['#view_mode'] == 'full' && isset($build['field_accessible_version'])) {

    // Set the longdesc attribute to a URL pointing to the infographic module's
    // route for outputing the long description.
    $args = ['node' => $entity->id()];
    $build['field_infographic'][0]['#item_attributes']['longdesc'] =
      Url::fromRoute('cgov_infographic.long_description', $args)->toString();
  }
}
