<?php

/**
 * @file
 * Contains cgov_infographic.install.
 */

use Drupal\cgov_core\CgovCoreTools;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function cgov_infographic_install() {
  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');

  // Add content type permissions.
  $siteHelper->addMediaTypePermissions('cgov_infographic', ['content_author']);
  $siteHelper->attachMediaTypeToWorkflow('cgov_infographic', 'editorial_workflow');

  // Install permissions for this module.
  _cgov_infographic_install_permissions($siteHelper);

}

/**
 * Installs permissions for this module.
 *
 * @param \Drupal\cgov_core\CgovCoreTools $siteHelper
 *   Cgov tools service.
 */
function _cgov_infographic_install_permissions(CgovCoreTools $siteHelper) {
  $perms = [
    'admin_ui' => [
      'access cgov_embedded_infographic_browser entity browser pages',
    ],
    'content_author' => [
      'revert any cgov_infographic media revisions',
      'view any cgov_infographic media revisions',
    ],
  ];

  $siteHelper->addRolePermissions($perms);
}

/**
 * Set permissions for editing media file revisions.
 */
function cgov_infographic_update_10001() {
  $siteHelper = \Drupal::service('cgov_core.tools');
  $perms = [
    'content_author' => [
      'revert any cgov_infographic media revisions',
      'view any cgov_infographic media revisions',
    ],
  ];
  $siteHelper->addRolePermissions($perms);
}

/**
 * Updates infographic body field format to ncids_streamlined.
 */
function cgov_infographic_update_10002() {
  $db = \Drupal::database();
  $bundle = 'cgov_infographic';

  // Media table updates.
  $db->update('media__body')
    ->fields(['body_format' => 'ncids_streamlined'])
    ->condition('bundle', $bundle)
    ->condition('body_format', 'full_html')
    ->execute();

  // Media revision table updates.
  $db->update('media_revision__body')
    ->fields(['body_format' => 'ncids_streamlined'])
    ->condition('bundle', $bundle)
    ->condition('body_format', 'full_html')
    ->execute();
}
