<?php

/**
 * @file
 * Contains cgov_media custom logic.
 */

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_field_widget_form_alter().
 *
 * Limits allowed text formats using the cgov_util form_tools service.
 *
 *  Using a less specific form alter due to media body field widget changes.
 */
function cgov_media_field_widget_form_alter(&$element, $form_state, $context) {
  // Maps field names to an array containing a single format.
  $map = [
    'body' => ['full_html'],
    'field_caption' => ['simple'],
  ];
  $formHelper = \Drupal::service('cgov_util.form_tools');
  $formHelper->allowTextFormats($map, $element, $context);
}

/**
 * Implements hook_entity_view_alter().
 *
 * Add attributes to media content types.
 */
function cgov_media_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  // If accessible text is available, add a link to an alternate version of the
  // page containing only the accessible text.
  // NOTE: $entity already reflects the current language, no need to switch
  // to another translation to check for availability.
  if ($entity->field_accessible_version != NULL &&
    (count($entity->field_accessible_version) > 0)) {

    // Set the longdesc attribute to a URL pointing to the infographic module's
    // route for outputing the long description.
    $args = ['media' => $entity->id()];

    // Find any field with a type of 'image' with the 'article' crop applied
    // and add the longdesc property to its attribute list.
    foreach ($build as $key => $properties) {
      if (substr($key, 0, 6) == 'field_' &&
        array_key_exists('#field_type', $properties)) {

        // Added if to prevent attempt at accessing the #field-type property if
        // it doesn't exist. (For whatever reason, evaluation doesn't seem to be
        // short-circuted when the other conditions are false.)
        if ($properties['#field_type'] == 'image' && $properties[0]["#image_style"] == 'cgov_article') {
          $build[$key][0]['#item_attributes']['longdesc'] =
            Url::fromRoute('cgov_media.long_description', $args)->toString();
        }
      }
    }
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * Workaround for odd behavior of the `getTableJoin()` method of the
 * `HandlerBase` of the `views` module, which leaves us without a table
 * alias for the queries used for sorting and filtering by bundle name.
 * If you find yourself with too much time on your hands, you might want
 * to track down enough information to file a bug report against Drupal
 * core.
 */
function cgov_media_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  $view_id = $view->id();
  if ($view_id === 'moderated_media') {
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if ($condition['field'] === '.bundle') {
          $condition['field'] = 'media.bundle';
        }
      }
    }
    foreach ($query->orderby as &$orderby) {
      if ($orderby['field'] === '.bundle') {
        $orderby['field'] = 'media.bundle';
      }
    }
  }
}
