<?php

/**
 * @file
 * Contains cgov_media custom logic.
 */

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * @file
 * Contains cgov_media.module.
 */

/**
 * Implements hook_field_widget_form_alter().
 *
 * Limits allowed text formats using the cgov_util form_tools service.
 */
function cgov_media_field_widget_form_alter(&$element, $form_state, $context) {
  // Maps field names to an array containing a single format.
  $map = [
    'body' => ['full_html'],
  ];
  $formHelper = \Drupal::service('cgov_util.form_tools');
  $formHelper->allowTextFormats($map, $element, $context);
}

/**
 * Implements hook_entity_view_alter().
 *
 * Add attributes to media content types.
 */
function cgov_media_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  // If accessible text is available, add a link to an alternate version of the
  // page containing only the accessible text.
  // NOTE: $entity already reflects the current language, no need to switch
  // to another translation to check for availability.
  if ($entity->field_accessible_version != NULL &&
    (count($entity->field_accessible_version) > 0)) {

    // Set the longdesc attribute to a URL pointing to the infographic module's
    // route for outputing the long description.
    $args = ['media' => $entity->id()];

    // Find any field with a type of 'image' with the 'article' crop applied
    // and add the longdesc property to its attribute list.
    foreach ($build as $key => $properties) {
      if (substr($key, 0, 6) == 'field_' &&
        array_key_exists('#field_type', $properties)) {

        // Added if to prevent attempt at accessing the #field-type property if
        // it doesn't exist. (For whatever reason, evaluation doesn't seem to be
        // short-circuted when the other conditions are false.)
        if ($properties['#field_type'] == 'image' && $properties[0]["#image_style"] == 'cgov_article') {
          $build[$key][0]['#item_attributes']['longdesc'] =
            Url::fromRoute('cgov_media.long_description', $args)->toString();
        }
      }
    }

  }

}
