<?php

/**
 * @file
 * Contains cgov_media.module.
 */

/**
 * Implements hook_field_widget_form_alter().
 *
 * Limits allowed text formats using the cgov_util form_tools service.
 */
function cgov_media_field_widget_form_alter(&$element, $form_state, $context) {
  // Maps field names to an array containing a single format.
  $map = [
    'body' => ['full_html'],
  ];
  $formHelper = \Drupal::service('cgov_util.form_tools');
  $formHelper->allowTextFormats($map, $element, $context);
}
