########
## Based on Lullabot Images
version: "3.7"

services:

  web:
    ## Use the web folder
    build:
      context: web
    volumes:
      ## The project root
      - ../:/var/www:cached
      ## Configs
      - ./web/runtime/apache2.conf:/etc/apache2/apache2.conf
      - ./web/runtime/php_apache2.ini:/etc/php/7.4/apache2/php.ini
      - ./web/runtime/php_cli.ini:/etc/php/7.4/cli/php.ini
      ## Block git repo management within the container
      - ./web/runtime/container-hooks:/var/www/scripts/hooks
      ## Npmrc for package installation.
      ## https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token
      ## You should only need read:packages if you are not someone
      ## that works with it frequently enough to know what this
      ## iss. (For read-only don't follow the npm login steps)
      - ~/.npmrc:/root/.npmrc
    env_file:
      - ./docker.env
    ports:
      - "80:80"
    networks:
      drupalvm:
        aliases:
          - simpletest
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - ./docker.env
    ports:
      - "3306:3306"
    networks:
      drupalvm:

networks:
  drupalvm:
