field.storage_settings.json_data:
  type: mapping
  label: 'Json data field settings'
  mapping:
    size:
      type: integer
      label: 'Size'
    json_schema_file:
      type: string
      label: 'JSON Schema File Uri'

field.field_settings.json_data:
  type: mapping
  label: 'Json data field settings'

field.value.json_data:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: text
      label: 'Value'


field.widget.settings.yaml_textarea:
  type: mapping
  label: 'Plain Text area (multiple rows)'
  mapping:
    rows:
      type: integer
      label: 'Rows'
    placeholder:
      type: label
      label: 'Placeholder'

field.formatter.settings.json_data_formatter:
  type: mapping
  label: 'JSON Data Field formatter'
