editor.editor.*.third_party.nci_ckeditor5_cleanup:
  type: nci_ckeditor5_cleanup.third_party_settings

nci_ckeditor5_cleanup.third_party_settings:
  type: mapping
  label: 'NCI CKEditor5 Cleanup third party editor settings'
  mapping:
    clean_styles:
      type: boolean
      label: 'Clean Styles'

