<?php

/**
 * @file
 * Contains cgov_external_link_block.module.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function cgov_external_link_block_field_widget_single_element_form_alter(&$element, &$form_state, $context) {

  if (
    $form_state->getBuildInfo()['form_id'] !== "block_content_cgov_external_link_block_edit_form" &&
    $form_state->getBuildInfo()['form_id'] !== "block_content_cgov_external_link_block_form" &&
    $form_state->getBuildInfo()['form_id'] !== "block_content_cgov_external_link_block_add_form"
  ) {
    return;
  }

  if (array_key_exists("#title", $element) && $element['#title'] == "Featured Item Url") {
    $element['uri']['#process'] = NULL;
  }
}

/**
 * Implements hook_views_query_alter().
 */
function cgov_external_link_block_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Check that we are altering the correct view.
  if ($view->id() == 'external_link_content_browser') {
    if ($query instanceof Sql) {
      $field_name = 'block_content_field_data.type';
      $excluded_values = [
        'content_block',
        'cgov_image_carousel',
        'ncids_mega_menu_content',
        'raw_html_block',
        'cgov_video_carousel',
      ];
      $query->addWhere(0, $field_name, $excluded_values, 'NOT IN');
    }
  }
}
