<?php

/**
 * @file
 * Contains cgov_cancer_center.install.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function cgov_cancer_center_install() {
  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');

  // Add content type permissions.
  $siteHelper->addContentTypePermissions('cgov_cancer_center', ['content_author']);
}

/**
 * Updates cancer center body field format to ncids_full_html.
 */
function cgov_cancer_center_update_8001() {
  $db = \Drupal::database();
  $bundle = 'cgov_cancer_center';

  // Node table updates.
  $db->update('node__body')
    ->fields(['body_format' => 'ncids_full_html'])
    ->condition('bundle', $bundle)
    ->condition('body_format', 'full_html')
    ->execute();

  // Node revision table updates.
  $db->update('node_revision__body')
    ->fields(['body_format' => 'ncids_full_html'])
    ->condition('bundle', $bundle)
    ->condition('body_format', 'full_html')
    ->execute();
}
