<?php

/**
 * @file
 * Contains cgov_home_landing.module.
 */

 /**
  * Implements hook_field_widget_form_alter().
  *
  * Limits allowed text formats using the cgov_util form_tools service.
  */
function cgov_home_landing_field_widget_form_alter(&$element, $form_state, $context) {
  // Maps field names to an array containing a single format.
  $map = [
    'field_raw_html' => ['raw_html'],
    'field_html_content' => ['full_html'],
  ];
  $formHelper = \Drupal::service('cgov_util.form_tools');
  $formHelper->allowTextFormats($map, $element, $context);
}
