<?php

/**
 * @file
 * Contains cgov_cthp.module.
 */

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function cgov_cthp_field_widget_single_element_form_alter(&$element, $form_state, $context) {

  // Remove autocomplete from external links.
  if (
    array_key_exists('#paragraph_type', $element) &&
    $element['#paragraph_type'] == 'cgov_cthp_feature_card_external'
  ) {
    // Make the autocomplete do nothing.
    $element['subform']['field_cthp_featured_url']['widget'][0]['uri']['#process'] = NULL;
  }
}
