<?php

/**
 * @file
 * Contains cgov_event.module.
 */

 use Drupal\Core\Entity\EntityTypeInterface;

 /**
 * Alter bundle field definitions.
 *
 * Implements hook_entity_bundle_field_info_alter.
 * This hook is only called when cache is rebuilt (drush cr).
 *
 * @param \Drupal\Core\Field\FieldDefinitionInterface[] $fields
 *   The array of bundle field definitions.
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 *   The entity type definition.
 * @param string $bundle
 *   The bundle.
 *
 * @todo WARNING: This hook will be changed in
 * https://www.drupal.org/node/2346347.
 */
function cgov_event_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'cgov_event') {
    if (!empty($fields['field_event_start_date'])) {
      // Add custom constraint to this field, that checks if end time is later than start time.
      // The parameter to addConstraint() is not the class name, but the ID defined in the
      // class annotation in EventStartEndTimeConstraint.php
      $fields['field_event_start_date']->addConstraint('CgovEventStartEndTimeConstraint', []);
    }
  }
}
