<?php

/**
 * @file
 * Contains cgov_video.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function cgov_video_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // The OEmbed video field attaches it's own label dynamically.
  // This lets us override that.
  if ($form_id == 'media_cgov_video_add_form') {
    // We extract the description made in the UI and override what is generated
    // by OembedWidget.
    $userCreatedDescription = $form['field_media_oembed_video']['widget']['#description'];
    $form['field_media_oembed_video']['widget'][0]['value']['#description'] = $userCreatedDescription;
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function cgov_video_media_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() != 'cgov_video') {
    return;
  }
  if (!empty($entity->field_override_thumbnail_video->target_id) && isset($build['field_override_thumbnail_video'])) {
    $build['thumbnail'] = $build['field_override_thumbnail_video'];
    unset($build['field_override_thumbnail_video']);
  }
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function cgov_video_field_widget_single_element_link_default_form_alter(&$element, FormStateInterface $form_state, $context) {
  if ($context['items']->getName() === 'field_audio_described_link') {
    $element['uri']['#description'] = t('Used to provide a link to the audio-described file. Enter the full URL starting with https://');
  }
}
