#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:$PATH

# Set git info.
git config --global user.name "Acquia Cloud"
git config --global user.email "noreply@acquia.com"

# Create MySQL DB.
mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"

## Let's setup the simpletest database here as well
mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS simpletest"
mysql -u root -proot -e "GRANT ALL ON simpletest.* to 'simpletest'@'%' IDENTIFIED BY 'simpletest'"

# Setup NVM.
nvm install v10.14.1
npm install -g npm

set +v
