#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:$PATH
export PHANTOMJS_CDNURL=https://cnpmjs.org/mirrors/phantomjs/

blt setup --define drush.alias='${drush.aliases.ci}' --environment=ci --no-interaction --ansi --verbose

set +v

