#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:${PATH}

## Setup Simpletest info for kernel & functional tests
export SIMPLETEST_BASE_URL=http://127.0.0.1:8888
export SIMPLETEST_DB=mysql://simpletest:simpletest@localhost/simpletest

blt tests:all --define drush.alias='${drush.aliases.ci}' --environment=ci --define tests.run-server=true -D behat.web-driver=chrome --yes --ansi --verbose

set +v
