#!/usr/bin/env bash

set -ev

export PATH=${COMPOSER_BIN}:${PATH}

blt tests:frontend:run --define drush.alias='${drush.aliases.ci}' --define tests.run-server=false --environment=ci --ansi --verbose --no-interaction

set +v
