#!/usr/bin/env bash
# This file is managed by Composer and should not be modified by end users. To
# override its default behavior, copy it into your project and modify
# acquia-pipelines.yml to call your custom version.

set -ev

export PATH=${PATH}:${COMPOSER_BIN}

blt validate:all --define drush.alias='${drush.aliases.ci}' --ansi --verbose

set +v
