<?php

/**
 * @file
 * Contains pdq_drug_information_summary.install.
 */

use Drupal\cgov_core\CgovCoreTools;

/**
 * Implements hook_install().
 *
 * Set up the site for Cancer Information Summaries.
 *
 * @see system_install()
 */
function pdq_drug_information_summary_install() {

  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');

  // Add content type permissions and assign to workflow.
  $restfulPermissions = [
    'restful get pdq_dis_api',
    'restful post pdq_dis_api',
  ];
  $siteHelper->addContentTypePermissions('pdq_drug_information_summary', ['pdq_importer'], CgovCoreTools::DEFAULT_PERMISSIONS);
  $siteHelper->addRolePermissions(['pdq_importer' => $restfulPermissions]);
}

/**
 * Add the PDQ DIS page type and disclaimer URL fields.
 */
function pdq_drug_information_summary_update_10001(): void {
  $features_manager = \Drupal::service('features.manager');
  $assigner = \Drupal::service('features_assigner');
  $assigner->assignConfigPackages();
  $features_manager->import(['pdq_drug_information_summary']);
}
