<?php

/**
 * @file
 * Contains pdq_drug_information_summary.install.
 */

use Drupal\cgov_core\CgovCoreTools;

/**
 * Implements hook_install().
 *
 * Set up the site for Cancer Information Summaries.
 *
 * @see system_install()
 */
function pdq_drug_information_summary_install() {

  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');

  // Add content type permissions and assign to workflow.
  $siteHelper->addContentTypePermissions('pdq_drug_information_summary', ['pdq_importer'], CgovCoreTools::DEFAULT_PERMISSIONS);
}

/**
 * Remove the PDQ DIS REST resource and its permissions.
 */
function pdq_drug_information_summary_update_10001() {
  \Drupal::configFactory()->getEditable('rest.resource.pdq_dis_api')->delete();
  $permissions = [
    'restful get pdq_dis_api',
    'restful post pdq_dis_api',
  ];
  $siteHelper = \Drupal::service('cgov_core.tools');
  $siteHelper->removeRolePermissions(['pdq_importer' => $permissions]);
}
