<?php

/**
 * @file
 * Contains cgov_article.module.
 */

/**
 * Implements hook_field_widget_form_alter().
 *
 * Limits allowed text formats using the cgov_core form_tools service.
 */
function cgov_article_field_widget_form_alter(&$element, $form_state, $context) {
  // Maps field names to an array containing a single format.
  $map = [
    'field_body_section_heading' => ['simple'],
    'field_body_section_content' => ['full_html'],
  ];
  $formHelper = \Drupal::service('cgov_core.form_tools');
  $formHelper->allowTextFormats($map, $element, $context);
}

/**
 * Update for v1.1.8.
 *
 * Install cgov_schema_org as a CGov Module.
 */
function cgov_article_update_8003() {
  if (!\Drupal::moduleHandler()->moduleExists('cgov_schema_org')) {
    $installer = \Drupal::service('module_installer');
    $installer->install(['cgov_schema_org']);
  }
}
