<?php

/**
 * @file
 * Contains cgov_cancer_research.install.
 */

/**
 * Remove Cancer Research Listing Page permissions from content authors.
 */
function cgov_cancer_research_update_10001(): void {
  $permissions = [
    'content_author' => [
      'create cgov_cancer_research content',
      'delete any cgov_cancer_research content',
      'delete own cgov_cancer_research content',
      'edit any cgov_cancer_research content',
      'edit own cgov_cancer_research content',
      'revert cgov_cancer_research revisions',
      'translate cgov_cancer_research node',
      'view cgov_cancer_research revisions',
    ],
  ];

  \Drupal::service('cgov_core.tools')->removeRolePermissions($permissions);
}
