excluded:
  - user.role.authenticated
  - user.role.content_author
  - user.role.content_editor
  - user.role.advanced_editor
  - user.role.layout_manager
  - user.role.site_admin
  - user.role.admin_ui
  - user.role.content_previewer
  - user.role.blog_manager
  - user.role.image_manager
  - user.role.pdq_importer
required:
  - pathauto.pattern.application_page_url
