<?php

/**
 * @file
 * Contains cgov_application_page.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 *
 * THIS MUST BE hook_entity NOT hook_ENTITY_TYPE or else pathauto will
 * not fire first.
 */
function cgov_application_page_entity_insert(EntityInterface $entity) {
  if ($entity->bundle() === 'cgov_application_page') {
    /* New entity then the app path never existed. Register.
     */
    $app_path_svc = \Drupal::service('app_module.app_path_manager');
    $app_path_svc->updateAppPath($entity);
  }
}

/**
 * Implements hook_entity_update().
 *
 * THIS MUST BE hook_entity NOT hook_ENTITY_TYPE or else pathauto will
 * not fire first.
 */
function cgov_application_page_entity_update(EntityInterface $entity) {
  if ($entity->bundle() === 'cgov_application_page') {
    /* Update the app path information, or create if it did not exist
     * before.
     */
    $app_path_svc = \Drupal::service('app_module.app_path_manager');
    $app_path_svc->updateAppPath($entity);
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * The insert and update hooks *MUST* come after pathauto.
 */
function cgov_application_page_module_implements_alter(&$implementations, $hook) {
  if ($hook !== 'entity_insert' && $hook !== 'entity_update') {
    return;
  }

  // Dutifully copying from the PHP docs to move our implementation
  // to the end of the list.
  $group = $implementations['cgov_application_page'];
  unset($implementations['cgov_application_page']);
  $implementations['cgov_application_page'] = $group;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function cgov_application_page_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $entity = _cgov_application_page_get_curr_entity();
  if ($entity && $entity->getEntityTypeId() === 'node' && $entity->bundle() === "cgov_application_page") {
    $content_type = $entity->bundle();
    $page_template = $entity->field_app_module_page_template->value;
    if ($page_template !== NULL) {
      $suggestions[] = 'page__' . $content_type . '__' . $page_template;
    }
  }
}

/**
 * Gets the current entity if there is one.
 *
 * @return Drupal\Core\Entity\ContentEntityInterface
 *   The retrieved entity, or FALSE if none found.
 */
function _cgov_application_page_get_curr_entity() {
  $params = \Drupal::routeMatch()->getParameters()->all();
  foreach ($params as $param) {
    if (!is_object($param)) {
      continue;
    }

    $class = new \ReflectionClass($param);

    if (in_array('Drupal\Core\Entity\ContentEntityInterface', $class->getInterfaceNames())) {
      // If you find a ContentEntityInterface stop iterating and return it.
      return $param;
    }
  }
  return FALSE;
}
