name: 'CGov Application Page'
type: module
package: 'CGov Digital Platform'
description: 'The Application Page content type'
core: 8.x
dependencies:
  - app_module
  - cgov_core
  - cgov_image
  - cgov_list
  - cgov_site_section
  - content_moderation
  - content_translation
  - datetime
  - entity_browser
  - entity_reference_revisions
  - field
  - language
  - link
  - metatag
  - metatag_dc
  - node
  - options
  - paragraphs
  - paragraphs_asymmetric_translation_widgets
  - path
  - pathauto
  - text
  - user
core_incompatible: false
