<?php

/**
 * @file
 * Contains cgov_application_page.install.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function cgov_application_page_install() {
  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');

  // Add content type permissions.
  $siteHelper->addContentTypePermissions('cgov_application_page', ['site_admin']);

}
