#!/bin/sh

STAGED=$(git diff --cached --name-only --diff-filter=ACM)
PHPCS=./vendor/bin/phpcs
if [ "$STAGED" != "" ]
then
    if [ ! -x $PHPCS ]
    then
        PHPCS=$(which phpcs 2>/dev/null)
	echo "PHPCS HAS BEEN SET TO $PHPCS"
    fi
    if [ ! -x $PHPCS ]
    then
        echo "phpcs is not installed ..."
        exit 1
    fi
    $PHPCS -e | grep -q DrupalPractice
    if [ $? -ne 0 ]
    then
        echo "The Drupal coding standards are not installed ..."
        exit 1
    fi
    echo "Checking compliance with Drupal coding standards ..."
    $PHPCS $STAGED
    if [ $? != 0 ]
    then
        echo "Fix the problems reported and try again ..."
        exit 1
    fi
fi
exit 0
